# Generated by Django 5.0.1 on 2024-02-10 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productcard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='header',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='price_type',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('UZS', 'UZS'), ('RUB', 'RUB')], default='RUB', max_length=200, null=True, verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='maincategories',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='ourpartner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ourpartner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='advantages',
            field=models.JSONField(blank=True, null=True, verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='firm',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Твердый'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('UZS', 'UZS'), ('RUB', 'RUB')], default='RUB', max_length=200, null=True, verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryProduct', to='shop.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='price_type',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('UZS', 'UZS'), ('RUB', 'RUB')], default='RUB', max_length=200, null=True, verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productCard', to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productImage', to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='main_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainCategories', to='shop.maincategories', verbose_name='Главная категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
    ]
