# Generated by Django 5.0.1 on 2024-01-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_type', models.CharField(blank=True, choices=[('USD', 'USD'), ('UZS', 'UZS'), ('RUB', 'RUB')], default='RUB', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'table_banner',
            },
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={'verbose_name': 'Consultant', 'verbose_name_plural': 'Consultants'},
        ),
        migrations.AlterModelOptions(
            name='ourpartner',
            options={'verbose_name': 'Our Partner', 'verbose_name_plural': 'Our Partners'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelTable(
            name='consultant',
            table='table_consultant',
        ),
        migrations.AlterModelTable(
            name='ourpartner',
            table='table_our_partner',
        ),
        migrations.AlterModelTable(
            name='product',
            table='table_product',
        ),
        migrations.AlterModelTable(
            name='service',
            table='table_service',
        ),
    ]
