# Generated by Django 5.0.1 on 2024-01-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_categories_maincategories_product_advantages_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='sub_category',
        ),
    ]
