# Generated by Django 5.0.1 on 2024-01-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_categories_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Categories', 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
